---
language: java
sudo: false
install: skip
dist: trusty

jdk:
  - oraclejdk8
  - openjdk8

cache:
  directories:
    - $HOME/.m2

git:
  depth: 3
  quiet: true

before_script: mvn clean -B -ff

script:
  - mvn verify -B -ff

after_success:
  - mvn coveralls:report -B -ff
