---
language: java
sudo: false
install: skip

matrix:
  include:
    - jdk: oraclejdk8
      dist: bionic
    - jdk: openjdk8
      dist: xenial

cache:
  directories:
    - $HOME/.m2

git:
  depth: 3
  quiet: true

before_script:
  - mvn clean -B -ff

script:
  - mvn verify -B -ff

after_success:
  - mvn coveralls:report -B -ff
