---
language: java
sudo: false
install: skip

addons:
  sonarcloud:
    organization: "tomerfi"

matrix:
  include:
    - jdk: oraclejdk8
      dist: trusty
      after_success:
        - ./mvnw sonar:sonar -Dsonar.host.url=https://sonarcloud.io -B -ff
    - jdk: openjdk8
      dist: xenial
      after_success:
        - ./mvnw coveralls:report -B -ff

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar/cache

git:
  depth: false

before_script:
  - chmod +x mvnw

script:
  - ./mvnw clean verify -B -ff
