---
language: java
sudo: false
install: skip

matrix:
  include:
    - jdk: oraclejdk8
      dist: trusty
      after_success:
        - ./mvnw sonar:sonar -Pcoverage -B -ff
    - jdk: openjdk8
      dist: xenial
      after_success:
        - ./mvnw coveralls:report -B -ff

cache:
  directories:
    - $HOME/.m2

git:
  depth: 3
  quiet: true

before_script:
  - chmod +x mvnw

script:
  - ./mvnw clean verify -B -ff
