---
language: java
sudo: false
install: skip

matrix:
  include:
    - jdk: oraclejdk8
      dist: trusty
    - jdk: openjdk8
      dist: xenial

cache:
  directories:
    - $HOME/.m2

git:
  depth: 3
  quiet: true

before_script:
  - mvnw clean -B -ff

script:
  - mvnw verify -B -ff

after_success:
  - mvnw coveralls:report -B -ff
