---
language: java
install: skip
os: linux
dist: trusty

addons:
  sonarcloud:
    organization: tomerfi

jdk:
  - oraclejdk8
  - openjdk8

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar/cache

git:
  depth: false
  quiet: true

before_script:
  - chmod +x mvnw

script:
  - ./mvnw clean verify -B -ff

after_success:
  - ./mvnw coveralls:report sonar:sonar -B -ff
